###################################
#Konfiguracija Planete top M no#82#
###################################
title: "One Space ✴ Away"
subtitle: "engaged 🌜 monkeys"
description: "✳ constellations ✳"
keywords:
author: Adnan Sulejmanović
language: ba
timezone: CET

index_generator:
  per_page: 7
  order_by: -date

archive_generator:
  per_page: 9
  yearly: true
  monthly: false
  daily: false
pagination_dir: warp

category_generator:
  per_page: 7

tag_generator:
  per_page: 5
  enable_index_page: false

url: https://sky.monkeyshub.space
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: nebula
archive_dir: constellations/
category_dir: darkmatter
code_dir: worm/hole
i18n_dir: :lang
skip_render:
  - "robots.txt"
  - animate/*
  - highlight/*

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: false
  field:
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

default_category: sagittarius
category_map:
tag_map:

meta_generator: true

date_format: DD.MM.YYYY
time_format: HH:mm
use_date_for_updated: true

theme: next

marked:
  # For preserve original quotes in code blocks.
  smartypants: false

search:
  path: search.json
  field: all

emoji:
  enable: true
  className: github-emoji
  styles:
  customEmojis:
